"""Add recurrence to reminder

Revision ID: 6f2fa40e4dc4
Revises: c5bdd1cb6eb3
Create Date: 2026-09-17 00:15:47.528966
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f2fa40e4dc4'
down_revision: Union[str, None] = 'c5bdd1cb6eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('recurrence', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'recurrence')
    # ### end Alembic commands ###

